### ISSUE TITLE
Mouse event - button

### ISSUE THREAD

**Issue by moobsmc** [avocadoboi/AvoGUI#1]
Hey! I was wondering if you could provide a simple example on how to register and listen for events on specific buttons? Ive been reading your documentation but can't seem to wrap my head around it.

Thank you.

**Comment by avocadoboi** [comment]
Hello! First, inherit AvoGUI::ButtonListener on the class that should receive button events, and let it override the method handleButtonClick(...) (this is where you respond to any button events). Then, call addButtonListener(...) on the button(s) you want to receive events from. 

I have added an example of this in test.cpp now. I'm happy you've found my library, it will hopefully soon be usable enough :^)

**Comment by moobsmc** [comment]
Thank you for the quick response! I got it working now, thank you for including the additional example.
