### ISSUE TITLE
Missing X11 on MacOS Big Sur

### ISSUE THREAD

**Issue by kaoti** [avocadoboi/AvoGUI#11]
Thats it, there is a way around it ? 
Edit (Apple MacBook Air m1 macOS v 11.2.3 (20D91))

**Comment by avocadoboi** [comment]
I'm sorry, there is not yet any support for MacOS in any of the versions of this framework. 

The old C++17 version of the framework had support for Windows and incomplete support for Linux. I have abandoned the C++17 version of the framework and started working on re-writing the whole thing in C++20 with a new and better design. I am planning to add support for MacOS. The current plan is to implement the new windowing module on all three platforms. I have started with Linux.

**Comment by kaoti** [comment]
Oh okay, there is no problem, thanks :)
