### ISSUE TITLE
Error when building examples

### ISSUE THREAD

**Issue by ewancg** [avocadoboi/AvoGUI#12]
``atomic_flag_deadlock.cpp:(.text._ZNSt6threadC2IRFvvEJEvEEOT_DpOT0_[_ZNSt6threadC5IRFvvEJEvEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'``

finding & linking the "Threads" package in cmake does nothing

adding the "-pthread" compile flag does nothing

**Comment by avocadoboi** [comment]
I see... I think I just forgot to link the Threads package to the atomic_flag_deadlock target. I think it should fix it. Maybe you linked it to the wrong target? I guess I haven't built that one on Linux yet. This example program doesn't really have anything to do with the library itself, it was just for reporting a bug to GCC. Maybe I should just remove it.
